/**
 * Constantes compartidas del humanizador de eventos de historial.
 * CAMPOS_EXCLUIDOS: campos técnicos internos que no se muestran al usuario.
 * ETIQUETAS: mapa de campo → nombre en español para la UI.
 */

export const CAMPOS_EXCLUIDOS = new Set([
  'id',
  'cliente_id',
  'negociacion_id',
  'vivienda_id',
  'proyecto_id',
  'usuario_id',
  'fuente_pago_id',
  'registrado_por',
  'usuario_registro',
  'usuario_creacion',
  'subido_por',
  'created_at',
  'updated_at',
  'fecha_creacion',
  'fecha_actualizacion',
  'version_actual',
  'version_lock',
  'fecha_ultima_modificacion',
  'activo',
  'fuente_pago_relacionada',
  'estado_documento',
  'razon_obsolescencia',
  'fecha_obsolescencia',
  'reemplazada_por',
  'razon_inactivacion',
  'fecha_inactivacion',
  'estado_fuente',
  'version_negociacion',
  'nombre_archivo',
  'nombre_original',
  'tamano_bytes',
  'tipo_mime',
  'es_version_actual',
  'documento_padre_id',
  'documento_identidad_url',
  'documento_identidad_titulo',
  'metadata',
  'etiquetas',
  'total_fuentes_pago',
  'total_abonado',
  'porcentaje_pagado',
  'porcentaje_completado',
  'nombre_completo',
])

export const ETIQUETAS: Record<string, string> = {
  // === CLIENTE ===
  nombres: 'Nombres',
  apellidos: 'Apellidos',
  tipo_documento: 'Tipo de documento',
  numero_documento: 'Número de documento',
  telefono: 'Teléfono',
  celular: 'Celular',
  telefono_alternativo: 'Teléfono alternativo',
  email: 'Correo electrónico',
  direccion: 'Dirección',
  ciudad: 'Ciudad',
  departamento: 'Departamento',
  barrio: 'Barrio',
  fecha_nacimiento: 'Fecha de nacimiento',
  estado_civil: 'Estado civil',
  estado: 'Estado',
  origen: 'Origen',
  referido_por: 'Referido por',
  ocupacion: 'Ocupación',
  empresa: 'Empresa',
  ingresos_mensuales: 'Ingresos mensuales',
  tipo_vivienda_actual: 'Tipo de vivienda actual',
  notas: 'Notas',
  // === NEGOCIACIÓN ===
  valor_negociado: 'Valor negociado',
  descuento_aplicado: 'Descuento aplicado',
  valor_total: 'Valor total',
  valor_total_pagar: 'Valor total a pagar',
  saldo_pendiente: 'Saldo pendiente',
  promesa_compraventa_url: 'Promesa de compraventa',
  promesa_firmada_url: 'Promesa firmada',
  escritura_url: 'Escritura',
  fecha_negociacion: 'Fecha de negociación',
  fecha_completada: 'Fecha de cierre',
  tipo_descuento: 'Tipo de descuento',
  motivo_descuento: 'Motivo del descuento',
  porcentaje_descuento: 'Porcentaje de descuento',
  valor_escritura_publica: 'Valor escritura pública',
  // === ABONO ===
  monto: 'Monto del abono',
  metodo_pago: 'Método de pago',
  fecha_abono: 'Fecha del abono',
  numero_referencia: 'Número de referencia',
  comprobante_url: 'Comprobante',
  // === RENUNCIA ===
  motivo: 'Motivo de renuncia',
  fecha_renuncia: 'Fecha de renuncia',
  monto_devolucion: 'Monto de devolución',
  monto_a_devolver: 'Monto a devolver',
  fecha_renuncia_efectiva: 'Fecha efectiva',
  // === INTERÉS ===
  presupuesto: 'Presupuesto',
  tipo_vivienda: 'Tipo de vivienda',
  // === DOCUMENTO ===
  titulo: 'Título',
  descripcion: 'Descripción',
  categoria_id: 'Categoría',
  url_storage: 'Archivo',
  fecha_documento: 'Fecha del documento',
  fecha_vencimiento: 'Fecha de vencimiento',
  es_importante: 'Marcado como importante',
  es_documento_identidad: 'Documento de identidad',
  tipo_documento_doc: 'Tipo de documento',
  observaciones: 'Observaciones',
  // === FUENTE DE PAGO ===
  tipo: 'Tipo de fuente',
  monto_aprobado: 'Monto aprobado',
  monto_recibido: 'Monto recibido',
  entidad: 'Entidad',
  carta_aprobacion_url: 'Carta de aprobación',
}
